-- Production migration blueprint. The local MVP uses data/db.json only.
CREATE TABLE organizations (id TEXT PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE', timezone TEXT NOT NULL DEFAULT 'Asia/Taipei', created_at TEXT NOT NULL);
CREATE TABLE users (id TEXT PRIMARY KEY, login_identifier TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, display_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE', created_at TEXT NOT NULL);
CREATE TABLE memberships (id TEXT PRIMARY KEY, tenant_id TEXT NULL REFERENCES organizations(id), user_id TEXT NOT NULL REFERENCES users(id), role TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE', UNIQUE(tenant_id, user_id));
CREATE TABLE sessions (id_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), membership_id TEXT NOT NULL REFERENCES memberships(id), expires_at TEXT NOT NULL, revoked_at TEXT NULL);
CREATE TABLE classes (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES organizations(id), name TEXT NOT NULL, academic_year TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE courses (id TEXT PRIMARY KEY, owner_tenant_id TEXT NOT NULL REFERENCES organizations(id), title TEXT NOT NULL, teacher_name TEXT NOT NULL, grade_range TEXT NOT NULL, status TEXT NOT NULL, draft_json TEXT NOT NULL, version_no INTEGER NOT NULL DEFAULT 0);
CREATE TABLE assignments (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES organizations(id), course_id TEXT NOT NULL REFERENCES courses(id), class_id TEXT NOT NULL REFERENCES classes(id), version_no INTEGER NOT NULL, due_at TEXT NULL);
CREATE TABLE submissions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES organizations(id), assignment_id TEXT NOT NULL REFERENCES assignments(id), student_membership_id TEXT NOT NULL REFERENCES memberships(id), answers_json TEXT NOT NULL, status TEXT NOT NULL, feedback TEXT NULL, score INTEGER NULL, submitted_at TEXT NOT NULL, reviewed_at TEXT NULL, UNIQUE(assignment_id, student_membership_id));
